// Code generated by pegz; DO NOT EDIT.
const std = @import("std");
const ast = @import("pegz_common").ast;
const interpreter = @import("pegz_common").interpreter;

// Init code
fn initParser(allocator: std.mem.Allocator) !void {
    _ = allocator;
    // Init code here
}

// Grammar data structure for interpreter
pub fn getGrammar(allocator: std.mem.Allocator) !*ast.Grammar {
    const grammar = try allocator.create(ast.Grammar);
    grammar.* = ast.Grammar{
        .pos = ast.Pos{ .line = 1, .column = 2, .offset = 0 },
        .init = null,
        .rules = std.ArrayList(*ast.Rule).init(allocator),
    };

    // Rule: Grammar
    // Rule: Initializer
    // Rule: Rule
    // Rule: Expression
    // Rule: ChoiceExpr
    // Rule: ActionExpr
    // Rule: SeqExpr
    // Rule: LabeledExpr
    // Rule: PrefixedExpr
    // Rule: PrefixedOp
    // Rule: SuffixedExpr
    // Rule: SuffixedOp
    // Rule: PrimaryExpr
    // Rule: RuleRefExpr
    // Rule: SemanticPredExpr
    // Rule: SemanticPredOp
    // Rule: RuleDefOp
    // Rule: SourceChar
    // Rule: Comment
    // Rule: MultiLineComment
    // Rule: MultiLineCommentNoLineTerminator
    // Rule: SingleLineComment
    // Rule: Identifier
    // Rule: IdentifierName
    // Rule: IdentifierStart
    // Rule: IdentifierPart
    // Rule: LitMatcher
    // Rule: StringLiteral
    // Rule: DoubleStringChar
    // Rule: SingleStringChar
    // Rule: RawStringChar
    // Rule: DoubleStringEscape
    // Rule: SingleStringEscape
    // Rule: CommonEscapeSequence
    // Rule: SingleCharEscape
    // Rule: OctalEscape
    // Rule: HexEscape
    // Rule: LongUnicodeEscape
    // Rule: ShortUnicodeEscape
    // Rule: OctalDigit
    // Rule: DecimalDigit
    // Rule: HexDigit
    // Rule: CharClassMatcher
    // Rule: ClassCharRange
    // Rule: ClassChar
    // Rule: CharClassEscape
    // Rule: UnicodeClassEscape
    // Rule: SingleCharUnicodeClass
    // Rule: UnicodeClass
    // Rule: AnyMatcher
    // Rule: CodeBlock
    // Rule: Code
    // Rule: __
    // Rule: _
    // Rule: Whitespace
    // Rule: EOL
    // Rule: EOS
    // Rule: EOF
    return grammar;
}

// Action function for rule: Grammar
fn onGrammar(c: *interpreter.Current, initializer: interpreter.Value, rules: interpreter.Value) !interpreter.Value {
    
    const pos = c.astPos();

    // create the grammar, assign its initializer
    const g = try c.allocator.create(ast.Grammar);
    g.* = ast.Grammar{
        .pos = pos,
        .init = null,
        .rules = std.ArrayList(*ast.Rule).init(c.allocator),
    };

    if (initializer) |init_val| {
        g.init = @as(*ast.CodeBlock, @ptrCast(init_val));
    }

    const rules_slice = @as([]const []const u8, @ptrCast(rules));
    for (rules_slice) |rule_val| {
        const rule_ptr = @as(*ast.Rule, @ptrCast(rule_val));
        try g.rules.append(c.allocator, rule_ptr);
    }

    return g;

}

// Action function for rule: Initializer
fn onInitializer(c: *interpreter.Current, code: interpreter.Value) !interpreter.Value {
    _ = c;
    
    return code;

}

// Action function for rule: Rule
fn onRule(c: *interpreter.Current, name: interpreter.Value, display: interpreter.Value, expr: interpreter.Value) !interpreter.Value {
    
    const pos = c.astPos();

    const rule = try c.allocator.create(ast.Rule);
    rule.* = ast.Rule{
        .pos = pos,
        .name = name.*,
        .display_name = undefined,
        .expression = undefined,
        .expr = undefined,
        .visited = false,
        .nullable = false,
        .left_recursive = false,
        .leader = false,
    };

    if (display) |display_val| {
        rule.display_name = @as(ast.StringLit, @ptrCast(display_val));
    } else {
        rule.display_name = ast.StringLit{
            .pos = pos,
            .value = "",
        };
    }

    const expr_ptr = try c.allocator.create(ast.Expression);
    expr_ptr.* = expr;
    rule.expr = expr_ptr;
    rule.expression = expr;

    return rule;

}

// Action function for rule: Expression
fn onExpression(c: *interpreter.Current) !interpreter.Value {
    _ = c;
}

// Action function for rule: ChoiceExpr
fn onChoiceExpr(c: *interpreter.Current, first: interpreter.Value, rest: interpreter.Value) !interpreter.Value {
    
    const rest_slice = @as([]const []const u8, @ptrCast(rest));
    if (rest_slice.len == 0) {
        return first;
    }

    const pos = c.astPos();
    const choice = try ast.ChoiceExpr.init(c.allocator, pos);
    try choice.alternatives.append(c.allocator, first);

    for (rest_slice) |sl| {
        const expr = @as(ast.Expression, @ptrCast(sl));
        try choice.alternatives.append(c.allocator, expr);
    }

    return ast.Expression{ .choice = choice };

}

// Action function for rule: ActionExpr
fn onActionExpr(c: *interpreter.Current, expr: interpreter.Value, code: interpreter.Value) !interpreter.Value {
    
    if (code == null) {
        return expr;
    }

    const pos = c.astPos();
    const act = try ast.ActionExpr.init(c.allocator, pos, expr, code.?, 0);
    return ast.Expression{ .action = act };

}

// Action function for rule: SeqExpr
fn onSeqExpr(c: *interpreter.Current, first: interpreter.Value, rest: interpreter.Value) !interpreter.Value {
    
    const rest_slice = @as([]const []const u8, @ptrCast(rest));
    if (rest_slice.len == 0) {
        return first;
    }
    const seq = try ast.SeqExpr.init(c.allocator, c.astPos());
    try seq.exprs.append(c.allocator, first);
    for (rest_slice) |sl| {
        const expr = @as(ast.Expression, @ptrCast(sl));
        try seq.exprs.append(c.allocator, expr);
    }
    return ast.Expression{ .seq = seq };

}

// Action function for rule: LabeledExpr
fn onLabeledExpr(c: *interpreter.Current, label: interpreter.Value, expr: interpreter.Value) !interpreter.Value {
    
    const pos = c.astPos();
    const lab = try c.allocator.create(ast.LabeledExpr);
    const label_ptr = try c.allocator.create(ast.Identifier);
    label_ptr.* = label.*;
    const expr_ptr = try c.allocator.create(ast.Expression);
    expr_ptr.* = expr;

    lab.* = ast.LabeledExpr{
        .pos = pos,
        .label = label_ptr,
        .expr = expr_ptr,
    };
    return ast.Expression{ .labeled = lab };

}

// Action function for rule: PrefixedExpr
fn onPrefixedExpr(c: *interpreter.Current, op: interpreter.Value, expr: interpreter.Value) !interpreter.Value {
    
    const pos = c.astPos();
    const op_str = @as([]const u8, @ptrCast(op));
    if (std.mem.eql(u8, op_str, "&")) {
        const and_expr = try ast.AndExpr.init(c.allocator, pos, expr);
        return ast.Expression{ .and_expr = and_expr };
    }
    const not_expr = try c.allocator.create(ast.NotExpr);
    const expr_ptr = try c.allocator.create(ast.Expression);
    expr_ptr.* = expr;
    not_expr.* = ast.NotExpr{
        .pos = pos,
        .expr = expr_ptr,
    };
    return ast.Expression{ .not = not_expr };

}

// Action function for rule: PrefixedOp
fn onPrefixedOp(c: *interpreter.Current) !interpreter.Value {
    
    return c.text;

}

// Action function for rule: SuffixedExpr
fn onSuffixedExpr(c: *interpreter.Current, expr: interpreter.Value, op: interpreter.Value) !interpreter.Value {
    
    const pos = c.astPos();
    const op_str = @as([]const u8, @ptrCast(op));
    const expr_ptr = try c.allocator.create(ast.Expression);
    expr_ptr.* = expr;

    if (std.mem.eql(u8, op_str, "?")) {
        const zero_or_one = try c.allocator.create(ast.ZeroOrOneExpr);
        zero_or_one.* = ast.ZeroOrOneExpr{
            .pos = pos,
            .expr = expr_ptr,
        };
        return ast.Expression{ .zero_or_one = zero_or_one };
    } else if (std.mem.eql(u8, op_str, "*")) {
        const zero_or_more = try c.allocator.create(ast.ZeroOrMoreExpr);
        zero_or_more.* = ast.ZeroOrMoreExpr{
            .pos = pos,
            .expr = expr_ptr,
        };
        return ast.Expression{ .zero_or_more = zero_or_more };
    } else if (std.mem.eql(u8, op_str, "+")) {
        const one_or_more = try c.allocator.create(ast.OneOrMoreExpr);
        one_or_more.* = ast.OneOrMoreExpr{
            .pos = pos,
            .expr = expr_ptr,
        };
        return ast.Expression{ .one_or_more = one_or_more };
    } else {
        return error.UnknownOperator;
    }

}

// Action function for rule: SuffixedOp
fn onSuffixedOp(c: *interpreter.Current) !interpreter.Value {
    
    return c.text;

}

// Action function for rule: PrimaryExpr
fn onPrimaryExpr(c: *interpreter.Current, expr: interpreter.Value) !interpreter.Value {
    _ = c;
    
    return expr;

}

// Action function for rule: RuleRefExpr
fn onRuleRefExpr(c: *interpreter.Current, name: interpreter.Value) !interpreter.Value {
    
    const ref = try c.allocator.create(ast.RuleRefExpr);
    const name_ptr = try c.allocator.create(ast.Identifier);
    name_ptr.* = name.*;
    ref.* = ast.RuleRefExpr{
        .pos = c.astPos(),
        .name = name_ptr,
        .nullable = false,
    };
    return ast.Expression{ .rule_ref = ref };

}

// Action function for rule: SemanticPredExpr
fn onSemanticPredExpr(c: *interpreter.Current, op: interpreter.Value, code: interpreter.Value) !interpreter.Value {
    
    const op_str = @as([]const u8, @ptrCast(op));
    if (std.mem.eql(u8, op_str, "&")) {
        const and_code = try c.allocator.create(ast.AndCodeExpr);
        and_code.* = ast.AndCodeExpr{
            .pos = c.astPos(),
            .code = code,
            .func_ix = 0,
        };
        return ast.Expression{ .and_code = and_code };
    }
    const not_code = try c.allocator.create(ast.NotCodeExpr);
    not_code.* = ast.NotCodeExpr{
        .pos = c.astPos(),
        .code = code,
        .func_ix = 0,
    };
    return ast.Expression{ .not_code = not_code };

}

// Action function for rule: SemanticPredOp
fn onSemanticPredOp(c: *interpreter.Current) !interpreter.Value {
    
    return c.text;

}

// Action function for rule: RuleDefOp
fn onRuleDefOp(c: *interpreter.Current) !interpreter.Value {
    _ = c;
}

// Action function for rule: SourceChar
fn onSourceChar(c: *interpreter.Current) !interpreter.Value {
    _ = c;
}

// Action function for rule: Comment
fn onComment(c: *interpreter.Current) !interpreter.Value {
    _ = c;
}

// Action function for rule: MultiLineComment
fn onMultiLineComment(c: *interpreter.Current) !interpreter.Value {
    _ = c;
}

// Action function for rule: MultiLineCommentNoLineTerminator
fn onMultiLineCommentNoLineTerminator(c: *interpreter.Current) !interpreter.Value {
    _ = c;
}

// Action function for rule: SingleLineComment
fn onSingleLineComment(c: *interpreter.Current) !interpreter.Value {
    _ = c;
}

// Action function for rule: Identifier
fn onIdentifier(c: *interpreter.Current) !interpreter.Value {
    _ = c;
}

// Action function for rule: IdentifierName
fn onIdentifierName(c: *interpreter.Current) !interpreter.Value {
    
    return ast.Identifier{
        .pos = c.astPos(),
        .value = try c.allocator.dupe(u8, c.text),
    };

}

// Action function for rule: IdentifierStart
fn onIdentifierStart(c: *interpreter.Current) !interpreter.Value {
    _ = c;
}

// Action function for rule: IdentifierPart
fn onIdentifierPart(c: *interpreter.Current) !interpreter.Value {
    _ = c;
}

// Action function for rule: LitMatcher
fn onLitMatcher(c: *interpreter.Current, lit: interpreter.Value, ignore: interpreter.Value) !interpreter.Value {
    
    const raw_str = lit.value;
    const unquoted = try std.mem.replaceOwned(u8, c.allocator, raw_str, "\"", "");
    const lit_matcher = try c.allocator.create(ast.LitMatcher);
    lit_matcher.* = ast.LitMatcher{
        .pos = c.astPos(),
        .value = unquoted,
        .ignore_case = ignore != null,
    };
    return ast.Expression{ .lit_matcher = lit_matcher };

}

// Action function for rule: StringLiteral
fn onStringLiteral(c: *interpreter.Current) !interpreter.Value {
    
    return ast.StringLit{
        .pos = c.astPos(),
        .value = try c.allocator.dupe(u8, c.text),
    };

}

// Action function for rule: DoubleStringChar
fn onDoubleStringChar(c: *interpreter.Current) !interpreter.Value {
    _ = c;
}

// Action function for rule: SingleStringChar
fn onSingleStringChar(c: *interpreter.Current) !interpreter.Value {
    _ = c;
}

// Action function for rule: RawStringChar
fn onRawStringChar(c: *interpreter.Current) !interpreter.Value {
    _ = c;
}

// Action function for rule: DoubleStringEscape
fn onDoubleStringEscape(c: *interpreter.Current) !interpreter.Value {
    _ = c;
}

// Action function for rule: SingleStringEscape
fn onSingleStringEscape(c: *interpreter.Current) !interpreter.Value {
    _ = c;
}

// Action function for rule: CommonEscapeSequence
fn onCommonEscapeSequence(c: *interpreter.Current) !interpreter.Value {
    _ = c;
}

// Action function for rule: SingleCharEscape
fn onSingleCharEscape(c: *interpreter.Current) !interpreter.Value {
    _ = c;
}

// Action function for rule: OctalEscape
fn onOctalEscape(c: *interpreter.Current) !interpreter.Value {
    _ = c;
}

// Action function for rule: HexEscape
fn onHexEscape(c: *interpreter.Current) !interpreter.Value {
    _ = c;
}

// Action function for rule: LongUnicodeEscape
fn onLongUnicodeEscape(c: *interpreter.Current) !interpreter.Value {
    _ = c;
}

// Action function for rule: ShortUnicodeEscape
fn onShortUnicodeEscape(c: *interpreter.Current) !interpreter.Value {
    _ = c;
}

// Action function for rule: OctalDigit
fn onOctalDigit(c: *interpreter.Current) !interpreter.Value {
    _ = c;
}

// Action function for rule: DecimalDigit
fn onDecimalDigit(c: *interpreter.Current) !interpreter.Value {
    _ = c;
}

// Action function for rule: HexDigit
fn onHexDigit(c: *interpreter.Current) !interpreter.Value {
    _ = c;
}

// Action function for rule: CharClassMatcher
fn onCharClassMatcher(c: *interpreter.Current) !interpreter.Value {
    
    const pos = c.astPos();
    const char_class = try c.allocator.create(ast.CharClassMatcher);
    const chars = std.ArrayList(u8).init(c.allocator);
    const ranges = std.ArrayList(struct { u8, u8 }).init(c.allocator);
    const unicode_classes = std.ArrayList([]const u8).init(c.allocator);

    char_class.* = ast.CharClassMatcher{
        .pos = pos,
        .value = try c.allocator.dupe(u8, c.text),
        .ignore_case = false,
        .inverted = false,
        .chars = chars,
        .ranges = ranges,
        .unicode_classes = unicode_classes,
    };
    return ast.Expression{ .char_class_matcher = char_class };

}

// Action function for rule: ClassCharRange
fn onClassCharRange(c: *interpreter.Current) !interpreter.Value {
    _ = c;
}

// Action function for rule: ClassChar
fn onClassChar(c: *interpreter.Current) !interpreter.Value {
    _ = c;
}

// Action function for rule: CharClassEscape
fn onCharClassEscape(c: *interpreter.Current) !interpreter.Value {
    _ = c;
}

// Action function for rule: UnicodeClassEscape
fn onUnicodeClassEscape(c: *interpreter.Current) !interpreter.Value {
    _ = c;
}

// Action function for rule: SingleCharUnicodeClass
fn onSingleCharUnicodeClass(c: *interpreter.Current) !interpreter.Value {
    _ = c;
}

// Action function for rule: UnicodeClass
fn onUnicodeClass(c: *interpreter.Current) !interpreter.Value {
    _ = c;
}

// Action function for rule: AnyMatcher
fn onAnyMatcher(c: *interpreter.Current) !interpreter.Value {
    
    const any_matcher = try c.allocator.create(ast.AnyMatcher);
    any_matcher.* = ast.AnyMatcher{
        .pos = c.astPos(),
        .value = try c.allocator.dupe(u8, c.text),
    };
    return ast.Expression{ .any_matcher = any_matcher };

}

// Action function for rule: CodeBlock
fn onCodeBlock(c: *interpreter.Current) !interpreter.Value {
    
    const pos = c.astPos();
    const code_block = try c.allocator.create(ast.CodeBlock);
    code_block.* = ast.CodeBlock{
        .pos = pos,
        .value = try c.allocator.dupe(u8, c.text),
    };
    return code_block;

}

// Action function for rule: Code
fn onCode(c: *interpreter.Current) !interpreter.Value {
    _ = c;
}

// Action function for rule: __
fn on__(c: *interpreter.Current) !interpreter.Value {
    _ = c;
}

// Action function for rule: _
fn on_(c: *interpreter.Current) !interpreter.Value {
    _ = c;
}

// Action function for rule: Whitespace
fn onWhitespace(c: *interpreter.Current) !interpreter.Value {
    _ = c;
}

// Action function for rule: EOL
fn onEOL(c: *interpreter.Current) !interpreter.Value {
    _ = c;
}

// Action function for rule: EOS
fn onEOS(c: *interpreter.Current) !interpreter.Value {
    _ = c;
}

// Action function for rule: EOF
fn onEOF(c: *interpreter.Current) !interpreter.Value {
    _ = c;
}

