const std = @import("std");
const ast = @import("ast.zig");
const interpreter_mod = @import("interpreter.zig");

// Helper function to escape strings for Zig code generation
fn escapeZigString(s: []const u8, allocator: std.mem.Allocator) ![]const u8 {
    var result = try std.ArrayList(u8).initCapacity(allocator, s.len * 2);
    errdefer {
        result.deinit(allocator);
    }

    for (s) |c| {
        switch (c) {
            '\\' => try result.appendSlice(allocator, "\\\\"),
            '"' => try result.appendSlice(allocator, "\\\""),
            '\n' => try result.appendSlice(allocator, "\\n"),
            '\r' => try result.appendSlice(allocator, "\\r"),
            '\t' => try result.appendSlice(allocator, "\\t"),
            else => try result.append(allocator, c),
        }
    }

    return result.toOwnedSlice(allocator);
}

/// Options configuration for the builder
pub const Options = struct {
    receiver_name: []const u8 = "c",
    optimize: bool = false,
    basic_latin_lookup_table: bool = false,
    global_state: bool = false,
    nolint: bool = false,
    support_left_recursion: bool = false,
};

/// Error types for builder operations
pub const BuilderError = error{
    GrammarError,
    LeftRecursionError,
    InvalidExpression,
    TemplateError,
    WriteFailed,
    OutOfMemory,
};

/// Template strings for generated code
const CODE_GENERATED_COMMENT = "";

// Template strings - in Zig we'll use comptime functions instead of templates
const ON_FUNC_TEMPLATE = "fn {s}(self *Self, {s}) any!error {{\n{s}\n}}\n";
const ON_PRED_FUNC_TEMPLATE = "fn {s}(self *Self, {s}) bool!error {{\n{s}\n}}\n";
const ON_STATE_FUNC_TEMPLATE = "fn {s}(self *Self, {s}) error! {{\n{s}\n}}\n";
const CALL_FUNC_TEMPLATE =
    \\fn call{s}(p *Self) any!error {{
    \\    return p.cur.{s}({s});
    \\}}
;
const CALL_PRED_FUNC_TEMPLATE =
    \\fn call{s}(p *Self) bool!error {{
    \\    return p.cur.{s}({s});
    \\}}
;
const CALL_STATE_FUNC_TEMPLATE =
    \\fn call{s}(p *Self) error! {{
    \\    return p.cur.{s}({s});
    \\}}
;

/// Builder generates parser code for a given grammar
pub const Builder = struct {
    allocator: std.mem.Allocator,
    writer: *std.io.Writer,
    err: ?BuilderError = null,

    // Options
    options: Options,

    // State
    rule_name: []const u8 = "",
    rule_index: usize = 0,       // Current rule index
    expr_index: usize = 0,       // Index for RuleRefExpr variables within current rule
    block_index: usize = 0,      // Index for block labels (Seq/Choice)
    args_stack: std.ArrayList(std.ArrayList([]const u8)),
    range_table: bool = false,

    pub fn init(allocator: std.mem.Allocator, writer: *std.io.Writer, options: Options) !Builder {
        return Builder{
            .allocator = allocator,
            .writer = writer,
            .options = options,
            .args_stack = try std.ArrayList(std.ArrayList([]const u8)).initCapacity(allocator, 0),
        };
    }

    /// BuildParser builds a PEG parser using the provided grammar
    pub fn buildParser(self: *Builder, grammar: *ast.Grammar) !void {
        std.debug.print("[Builder] buildParser: start\n", .{});

        // Prepare and validate grammar (simplified version)
        const have_left_recursion = try self.prepareGrammar(grammar);

        if (!self.options.support_left_recursion and have_left_recursion) {
            self.err = BuilderError.LeftRecursionError;
            return BuilderError.LeftRecursionError;
        }

        // Write basic module header - only the required code generated comment
        try self.writer.writeAll("// Code generated by pegz; DO NOT EDIT.\n");
        try self.writer.writeAll("const std = @import(\"std\");\n");
        try self.writer.writeAll("const ast = @import(\"pegz_common\").ast;\n");
        try self.writer.writeAll("const interpreter = @import(\"pegz_common\").interpreter;\n\n");
        std.debug.print("[Builder] buildParser: Wrote module header\n", .{});

        // Write the different sections
        try self.writeInit(grammar.init);
        std.debug.print("[Builder] buildParser: Wrote init\n", .{});

        try self.writeGrammar(grammar);
        std.debug.print("[Builder] buildParser: Wrote grammar\n", .{});

        for (grammar.rules.items) |rule| {
            std.debug.print("[Builder] buildParser: Writing rule '{s}'\n", .{rule.name.value});
            try self.writeRuleCode(rule);
        }

        // Write parse() entry function
        try self.writeParseFunction(grammar);

        std.debug.print("[Builder] buildParser: end\n", .{});
    }

    fn prepareGrammar(self: *Builder, grammar: *ast.Grammar) !bool {
        _ = self;
        _ = grammar;
        // This would implement grammar preparation and left recursion detection
        // For now, return false (no left recursion detected)
        return false;
    }

    fn writeInit(self: *Builder, init_code: ?*ast.CodeBlock) !void {
        if (init_code) |_| {
            // Write init code block
            try self.writer.writeAll("// Init code\n");
            try self.writer.writeAll("fn initParser(allocator: std.mem.Allocator) !void {\n");
            try self.writer.writeAll("    _ = allocator;\n");
            // TODO: Process the code block and extract Zig code
            // For now, skip the content
            try self.writer.writeAll("    // Init code here\n");
            try self.writer.writeAll("}\n\n");
        }
    }

    fn writeGrammar(self: *Builder, g: *ast.Grammar) !void {
        // Generate grammar structure for interpreter
        try self.writer.writeAll("// Grammar data structure\n");
        try self.writer.writeAll("pub fn getGrammar(allocator: std.mem.Allocator) !*ast.Grammar {\n");

        try self.writer.writeAll("    const grammar = try allocator.create(ast.Grammar);\n");
        try self.writer.writeAll("    grammar.* = ast.Grammar{\n");
        try self.writer.print("        .pos = ast.Pos{{ .line = {}, .column = {}, .offset = {} }},\n", .{g.pos.line, g.pos.column, g.pos.offset});
        try self.writer.writeAll("        .init = null,\n");
        try self.writer.print("        .rules = std.ArrayList(*ast.Rule).initCapacity(allocator, {}) catch unreachable,\n", .{g.rules.items.len});
        try self.writer.writeAll("    };\n\n");

        // Phase 1: Generate rule structures and expressions
        // rule_ref variables will be declared inline in writeExprForAST
        for (g.rules.items, 0..) |rule, i| {
            self.rule_index = i;

            // Reset expr_index for generating expressions
            self.expr_index = 0;

            // Generate the expression AST first with error handling
            const expr_result = self.writeExprForAST(rule.expr) catch |err| {
                std.debug.print("ERROR generating expr for rule '{s}': {}\n", .{rule.name.value, err});
                continue;
            };

            // Now generate the rule
            try self.writer.writeAll("    {\n");
            try self.writer.writeAll("        const r = try allocator.create(ast.Rule);\n");
            try self.writer.writeAll("        r.* = ast.Rule{\n");

            // Position
            const pos = rule.pos;
            try self.writer.print("            .pos = ast.Pos{{ .line = {}, .column = {}, .offset = {} }},\n", .{pos.line, pos.column, pos.offset});

            // Name
            const escaped_name = try escapeZigString(rule.name.value, self.allocator);
            defer self.allocator.free(escaped_name);
            try self.writer.print("            .name = ast.Identifier{{ .pos = ast.Pos{{ .line = {}, .column = {}, .offset = {} }}, .value = \"{s}\" }},\n",
                .{rule.name.pos.line, rule.name.pos.column, rule.name.pos.offset, escaped_name});

            // Display name
            if (rule.display_name.value.len > 0) {
                const escaped_display = try escapeZigString(rule.display_name.value, self.allocator);
                defer self.allocator.free(escaped_display);
                try self.writer.print("            .display_name = ast.StringLit{{ .pos = ast.Pos{{ .line = {}, .column = {}, .offset = {} }}, .value = \"{s}\" }},\n",
                    .{rule.display_name.pos.line, rule.display_name.pos.column, rule.display_name.pos.offset, escaped_display});
            } else {
                try self.writer.writeAll("            .display_name = ast.StringLit{\n");
                try self.writer.writeAll("                .pos = ast.Pos{ .line = 0, .column = 0, .offset = 0 },\n");
                try self.writer.writeAll("                .value = \"\",\n");
                try self.writer.writeAll("            },\n");
            }

            // Expression value and pointer
            // For now, set .expression to undefined and use .expr pointer
            try self.writer.writeAll("            .expression = undefined,\n");
            try self.writer.print("            .expr = {s},\n", .{expr_result.name});
            // TODO: manage memory properly
            _ = expr_result.is_rule_ref;

            // Other fields
            try self.writer.writeAll("            .visited = false,\n");
            try self.writer.writeAll("            .nullable = false,\n");
            try self.writer.writeAll("            .left_recursive = false,\n");
            try self.writer.writeAll("            .leader = false,\n");

            try self.writer.writeAll("        };\n");
            try self.writer.writeAll("        try grammar.rules.append(allocator, r);\n");
            try self.writer.writeAll("    }\n");
        }

        try self.writer.writeAll("    return grammar;\n");
        try self.writer.writeAll("}\n\n");
    }

    /// Write expression value (inline, not pointer)
    fn writeExprValue(self: *Builder, expr: *ast.Expression) !void {
        try self.writer.writeAll("ast.Expression{");
        switch (expr.*) {
            .seq => |seq| {
                try self.writer.writeAll(".seq = ast.SeqExpr{");
                try self.writer.print(" .pos = ast.Pos{{ .line = {}, .column = {}, .offset = {} }}, ",
                    .{seq.pos.line, seq.pos.column, seq.pos.offset});
                try self.writer.writeAll(".exprs = undefined, .nullable = false }");
            },
            .choice => |choice| {
                try self.writer.writeAll(".choice = ast.ChoiceExpr{");
                try self.writer.print(" .pos = ast.Pos{{ .line = {}, .column = {}, .offset = {} }}, ",
                    .{choice.pos.line, choice.pos.column, choice.pos.offset});
                try self.writer.writeAll(".alternatives = undefined, .nullable = false }");
            },
            else => {
                try self.writer.writeAll(".seq = undefined");
            },
        }
        try self.writer.writeAll("}");
    }

    /// Generate expression AST data structure (for interpreter mode)
    fn writeExprForAST(self: *Builder, expr: *ast.Expression) !struct { name: []const u8, is_rule_ref: bool } {
        // Handle rule_ref - generate declaration and return wrapper name
        if (expr.* == .rule_ref) {
            self.expr_index += 1;
            const rule_ref = expr.rule_ref;

            // Generate rule_ref declaration
            const escaped_name = try escapeZigString(rule_ref.name.value, self.allocator);
            defer self.allocator.free(escaped_name);

            try self.writer.print("    const rule_ref_{}_{} = try allocator.create(ast.RuleRefExpr);\n", .{self.rule_index, self.expr_index});
            try self.writer.print("    rule_ref_{}_{}.* = .{{\n", .{self.rule_index, self.expr_index});
            try self.writer.print("        .pos = ast.Pos{{ .line = {}, .column = {}, .offset = {} }},\n",
                .{ rule_ref.pos.line, rule_ref.pos.column, rule_ref.pos.offset });
            try self.writer.print("        .name = .{{\n            .pos = ast.Pos{{ .line = {}, .column = {}, .offset = {} }},\n            .value = \"{s}\",\n        }},\n",
                .{rule_ref.name.pos.line, rule_ref.name.pos.column, rule_ref.name.pos.offset, escaped_name});
            try self.writer.writeAll("        .nullable = false,\n");
            try self.writer.print("    }};\n", .{});

            // Generate Expression wrapper
            const wrapper_name = try std.fmt.allocPrint(self.allocator, "rule_ref_expr_{d}_{d}",
                .{self.rule_index, self.expr_index});
            try self.writer.print("    const {s} = try allocator.create(ast.Expression);\n", .{wrapper_name});
            try self.writer.print("    {s}.* = .{{ .rule_ref = rule_ref_{}_{} }};\n\n", .{wrapper_name, self.rule_index, self.expr_index});

            return .{ .name = wrapper_name, .is_rule_ref = true };
        }

        // For other expression types, generate the structure
        // Increment expr_index for this expression
        self.expr_index += 1;
        const current_expr_index = self.expr_index;

        // Generate unique variable name for this expression
        const var_name = try std.fmt.allocPrint(self.allocator, "expr_{d}_{d}", .{self.rule_index, current_expr_index});
        errdefer self.allocator.free(var_name);

        try self.writer.print("    const {s} = try allocator.create(ast.Expression);\n", .{var_name});
        try self.writer.writeAll("    {\n");

        switch (expr.*) {
            .seq => |seq| {
                try self.writer.print("        const seq_{} = try allocator.create(ast.SeqExpr);\n", .{current_expr_index});
                try self.writer.print("        seq_{}.* = .{{\n", .{current_expr_index});
                try self.writer.print("            .pos = ast.Pos{{ .line = {}, .column = {}, .offset = {} }},\n",
                    .{seq.pos.line, seq.pos.column, seq.pos.offset});
                try self.writer.writeAll("            .exprs = std.ArrayList(*ast.Expression).initCapacity(allocator, ");
                try self.writer.print("{}) catch unreachable,\n", .{seq.exprs.items.len});
                try self.writer.writeAll("            .nullable = false,\n");
                try self.writer.writeAll("        };\n");

                // Now generate sub-expressions and add them
                for (seq.exprs.items) |sub_expr| {
                    const sub_var = try self.writeExprForAST(sub_expr);
                    try self.writer.print("        try seq_{}.exprs.append(allocator, {s});\n", .{current_expr_index, sub_var.name});
                    _ = sub_var.is_rule_ref;
                }

                try self.writer.print("        {s}.* = .{{ .seq = seq_{} }};\n", .{var_name, current_expr_index});
            },
            .choice => |choice| {
                try self.writer.print("        const choice_{} = try allocator.create(ast.ChoiceExpr);\n", .{current_expr_index});
                try self.writer.print("        choice_{}.* = .{{\n", .{current_expr_index});
                try self.writer.print("            .pos = ast.Pos{{ .line = {}, .column = {}, .offset = {} }},\n",
                    .{choice.pos.line, choice.pos.column, choice.pos.offset});
                try self.writer.writeAll("            .alternatives = std.ArrayList(*ast.Expression).initCapacity(allocator, ");
                try self.writer.print("{}) catch unreachable,\n", .{choice.alternatives.items.len});
                try self.writer.writeAll("            .nullable = false,\n");
                try self.writer.writeAll("        };\n");

                // Generate sub-expressions
                for (choice.alternatives.items) |alt| {
                    const alt_var = try self.writeExprForAST(alt);
                    try self.writer.print("        try choice_{}.alternatives.append(allocator, {s});\n", .{current_expr_index, alt_var.name});
                    _ = alt_var.is_rule_ref;
                }

                try self.writer.print("        {s}.* = .{{ .choice = choice_{} }};\n", .{var_name, current_expr_index});
            },
            .action => |act| {
                // Create and initialize code block first
                const escaped_code = try escapeZigString(act.code.value, self.allocator);
                defer self.allocator.free(escaped_code);
                try self.writer.print("        const code_{} = try allocator.create(ast.CodeBlock);\n", .{current_expr_index});
                try self.writer.print("        code_{}.* = .{{\n", .{current_expr_index});
                try self.writer.print("            .pos = ast.Pos{{ .line = {}, .column = {}, .offset = {} }},\n",
                    .{act.code.pos.line, act.code.pos.column, act.code.pos.offset});
                try self.writer.print("            .value = \"{s}\",\n", .{escaped_code});
                try self.writer.writeAll("        };\n");

                // Now create action expression
                try self.writer.print("        const action_{} = try allocator.create(ast.ActionExpr);\n", .{current_expr_index});
                try self.writer.print("        action_{}.* = .{{\n", .{current_expr_index});
                try self.writer.print("            .pos = ast.Pos{{ .line = {}, .column = {}, .offset = {} }},\n",
                    .{act.pos.line, act.pos.column, act.pos.offset});
                try self.writer.writeAll("            .expr = undefined,\n");
                try self.writer.print("            .code = code_{},\n", .{current_expr_index});
                try self.writer.writeAll("            .func_ix = 0,\n");
                try self.writer.writeAll("            .nullable = false,\n");
                try self.writer.writeAll("        };\n");

                // Generate sub-expression for action
                const sub_var = try self.writeExprForAST(act.expr);
                try self.writer.print("        action_{}.expr = {s};\n", .{current_expr_index, sub_var.name});
                _ = sub_var.is_rule_ref;

                try self.writer.print("        {s}.* = .{{ .action = action_{} }};\n", .{var_name, current_expr_index});
            },
            .labeled => |labeled| {
                // Create and initialize label identifier first
                const escaped_label = try escapeZigString(labeled.label.value, self.allocator);
                defer self.allocator.free(escaped_label);
                try self.writer.print("        const label_{} = try allocator.create(ast.Identifier);\n", .{current_expr_index});
                try self.writer.print("        label_{}.* = .{{\n", .{current_expr_index});
                try self.writer.print("            .pos = ast.Pos{{ .line = {}, .column = {}, .offset = {} }},\n",
                    .{labeled.label.pos.line, labeled.label.pos.column, labeled.label.pos.offset});
                try self.writer.print("            .value = \"{s}\",\n", .{escaped_label});
                try self.writer.writeAll("        };\n");

                // Now create labeled expression
                try self.writer.print("        const labeled_{} = try allocator.create(ast.LabeledExpr);\n", .{current_expr_index});
                try self.writer.print("        labeled_{}.* = .{{\n", .{current_expr_index});
                try self.writer.print("            .pos = ast.Pos{{ .line = {}, .column = {}, .offset = {} }},\n",
                    .{labeled.pos.line, labeled.pos.column, labeled.pos.offset});
                try self.writer.print("            .label = label_{},\n", .{current_expr_index});
                try self.writer.writeAll("            .expr = undefined,\n");
                try self.writer.writeAll("        };\n");

                // Generate sub-expression
                const sub_var = try self.writeExprForAST(labeled.expr);
                try self.writer.print("        labeled_{}.expr = {s};\n", .{current_expr_index, sub_var.name});
                _ = sub_var.is_rule_ref;

                try self.writer.print("        {s}.* = .{{ .labeled = labeled_{} }};\n", .{var_name, current_expr_index});
            },
            .and_expr => |and_expr| {
                try self.writer.print("        const and_expr_{} = try allocator.create(ast.AndExpr);\n", .{current_expr_index});
                try self.writer.print("        and_expr_{}.* = .{{\n", .{current_expr_index});
                try self.writer.print("            .pos = ast.Pos{{ .line = {}, .column = {}, .offset = {} }},\n",
                    .{and_expr.pos.line, and_expr.pos.column, and_expr.pos.offset});
                try self.writer.writeAll("            .expr = undefined,\n");
                try self.writer.writeAll("        };\n");

                const sub_var = try self.writeExprForAST(and_expr.expr);
                try self.writer.print("        and_expr_{}.expr = {s};\n", .{current_expr_index, sub_var.name});
                _ = sub_var.is_rule_ref;

                try self.writer.print("        {s}.* = .{{ .and_expr = and_expr_{} }};\n", .{var_name, current_expr_index});
            },
            .not => |not_expr| {
                try self.writer.print("        const not_expr_{} = try allocator.create(ast.NotExpr);\n", .{current_expr_index});
                try self.writer.print("        not_expr_{}.* = .{{\n", .{current_expr_index});
                try self.writer.print("            .pos = ast.Pos{{ .line = {}, .column = {}, .offset = {} }},\n",
                    .{not_expr.pos.line, not_expr.pos.column, not_expr.pos.offset});
                try self.writer.writeAll("            .expr = undefined,\n");
                try self.writer.writeAll("        };\n");

                const sub_var = try self.writeExprForAST(not_expr.expr);
                try self.writer.print("        not_expr_{}.expr = {s};\n", .{current_expr_index, sub_var.name});
                _ = sub_var.is_rule_ref;

                try self.writer.print("        {s}.* = .{{ .not = not_expr_{} }};\n", .{var_name, current_expr_index});
            },
            .zero_or_one => |z| {
                try self.writer.print("        const zero_or_one_{} = try allocator.create(ast.ZeroOrOneExpr);\n", .{current_expr_index});
                try self.writer.print("        zero_or_one_{}.* = .{{\n", .{current_expr_index});
                try self.writer.print("            .pos = ast.Pos{{ .line = {}, .column = {}, .offset = {} }},\n",
                    .{z.pos.line, z.pos.column, z.pos.offset});
                try self.writer.writeAll("            .expr = undefined,\n");
                try self.writer.writeAll("        };\n");

                const sub_var = try self.writeExprForAST(z.expr);
                try self.writer.print("        zero_or_one_{}.expr = {s};\n", .{current_expr_index, sub_var.name});
                _ = sub_var.is_rule_ref;

                try self.writer.print("        {s}.* = .{{ .zero_or_one = zero_or_one_{} }};\n", .{var_name, current_expr_index});
            },
            .zero_or_more => |z| {
                try self.writer.print("        const zero_or_more_{} = try allocator.create(ast.ZeroOrMoreExpr);\n", .{current_expr_index});
                try self.writer.print("        zero_or_more_{}.* = .{{\n", .{current_expr_index});
                try self.writer.print("            .pos = ast.Pos{{ .line = {}, .column = {}, .offset = {} }},\n",
                    .{z.pos.line, z.pos.column, z.pos.offset});
                try self.writer.writeAll("            .expr = undefined,\n");
                try self.writer.writeAll("        };\n");

                const sub_var = try self.writeExprForAST(z.expr);
                try self.writer.print("        zero_or_more_{}.expr = {s};\n", .{current_expr_index, sub_var.name});
                _ = sub_var.is_rule_ref;

                try self.writer.print("        {s}.* = .{{ .zero_or_more = zero_or_more_{} }};\n", .{var_name, current_expr_index});
            },
            .one_or_more => |o| {
                try self.writer.print("        const one_or_more_{} = try allocator.create(ast.OneOrMoreExpr);\n", .{current_expr_index});
                try self.writer.print("        one_or_more_{}.* = .{{\n", .{current_expr_index});
                try self.writer.print("            .pos = ast.Pos{{ .line = {}, .column = {}, .offset = {} }},\n",
                    .{o.pos.line, o.pos.column, o.pos.offset});
                try self.writer.writeAll("            .expr = undefined,\n");
                try self.writer.writeAll("        };\n");

                const sub_var = try self.writeExprForAST(o.expr);
                try self.writer.print("        one_or_more_{}.expr = {s};\n", .{current_expr_index, sub_var.name});
                _ = sub_var.is_rule_ref;

                try self.writer.print("        {s}.* = .{{ .one_or_more = one_or_more_{} }};\n", .{var_name, current_expr_index});
            },
            .lit_matcher => |lit| {
                const escaped_val = try escapeZigString(lit.value, self.allocator);
                defer self.allocator.free(escaped_val);

                try self.writer.print("        const lit_{} = try allocator.create(ast.LitMatcher);\n", .{current_expr_index});
                try self.writer.print("        lit_{}.* = .{{\n", .{current_expr_index});
                try self.writer.print("            .pos = ast.Pos{{ .line = {}, .column = {}, .offset = {} }},\n",
                    .{lit.pos.line, lit.pos.column, lit.pos.offset});
                try self.writer.print("            .value = \"{s}\",\n", .{escaped_val});
                try self.writer.print("            .ignore_case = {},\n", .{lit.ignore_case});
                try self.writer.writeAll("        };\n");

                try self.writer.print("        {s}.* = .{{ .lit_matcher = lit_{} }};\n", .{var_name, current_expr_index});
            },
            .any_matcher => |any| {
                try self.writer.print("        const any_{} = try allocator.create(ast.AnyMatcher);\n", .{current_expr_index});
                try self.writer.print("        any_{}.* = .{{\n", .{current_expr_index});
                try self.writer.print("            .pos = ast.Pos{{ .line = {}, .column = {}, .offset = {} }},\n",
                    .{any.pos.line, any.pos.column, any.pos.offset});
                try self.writer.print("            .value = \"{s}\",\n", .{any.value});
                try self.writer.writeAll("        };\n");

                try self.writer.print("        {s}.* = .{{ .any_matcher = any_{} }};\n", .{var_name, current_expr_index});
            },
            .char_class_matcher => |class| {
                try self.writer.print("        const char_class_{} = try allocator.create(ast.CharClassMatcher);\n", .{current_expr_index});
                try self.writer.print("        char_class_{}.* = .{{\n", .{current_expr_index});
                try self.writer.print("            .pos = ast.Pos{{ .line = {}, .column = {}, .offset = {} }},\n",
                    .{class.pos.line, class.pos.column, class.pos.offset});

                // value and ignore_case fields
                const escaped_value = try escapeZigString(class.value, self.allocator);
                defer self.allocator.free(escaped_value);
                try self.writer.print("            .value = \"{s}\",\n", .{escaped_value});
                try self.writer.print("            .ignore_case = {},\n", .{class.ignore_case});
                try self.writer.print("            .inverted = {},\n", .{class.inverted});

                try self.writer.writeAll("            .ranges = std.ArrayList(struct { u8, u8 }).initCapacity(allocator, ");
                try self.writer.print("{}) catch unreachable,\n", .{class.ranges.items.len});
                try self.writer.writeAll("            .chars = std.ArrayList(u8).initCapacity(allocator, ");
                try self.writer.print("{}) catch unreachable,\n", .{class.chars.items.len});
                try self.writer.writeAll("            .unicode_classes = std.ArrayList([]const u8).initCapacity(allocator, ");
                try self.writer.print("{}) catch unreachable,\n", .{class.unicode_classes.items.len});
                try self.writer.writeAll("        };\n");

                // Add ranges
                for (class.ranges.items) |r| {
                    // Output: try char_class_N.ranges.append(allocator, .{ a, b });
                    try self.writer.print("        try char_class_{}.ranges.append(allocator, .{{ {}, {} }});\n",
                        .{current_expr_index, r[0], r[1]});
                }

                // Add chars
                for (class.chars.items) |c| {
                    try self.writer.print("        try char_class_{}.chars.append(allocator, {});\n",
                        .{current_expr_index, c});
                }

                // Add unicode_classes
                for (class.unicode_classes.items) |uc| {
                    const escaped = try escapeZigString(uc, self.allocator);
                    defer self.allocator.free(escaped);
                    try self.writer.print("        try char_class_{}.unicode_classes.append(allocator, \"{s}\");\n",
                        .{current_expr_index, escaped});
                }

                try self.writer.print("        {s}.* = .{{ .char_class_matcher = char_class_{} }};\n", .{var_name, current_expr_index});
            },
            else => {
                // For other expression types, return undefined
                try self.writer.print("        {s}.* = undefined;\n", .{var_name});
                try self.writer.writeAll("    }\n");
                return .{ .name = var_name, .is_rule_ref = false };
            },
        }

        try self.writer.writeAll("    }\n");

        return .{ .name = var_name, .is_rule_ref = false };
    }

    fn writeParseFunction(self: *Builder, grammar: *ast.Grammar) !void {
        _ = grammar;

        try self.writer.writeAll("\n// Parse entry function\n");
        try self.writer.writeAll("// Note: This returns a static grammar template, not a dynamically parsed one\n");
        try self.writer.writeAll("pub fn parse(allocator: std.mem.Allocator, filename: []const u8, source: []const u8) !*ast.Grammar {\n");
        try self.writer.writeAll("    _ = filename;\n");
        try self.writer.writeAll("    _ = source;\n");
        try self.writer.writeAll("    // Get the static grammar structure\n");
        try self.writer.writeAll("    return getGrammar(allocator);\n");
        try self.writer.writeAll("}\n");
    }

    // Declare all RuleRefExpr variables in an expression tree
    fn declareRuleRefExprs(self: *Builder, expr: *ast.Expression) BuilderError!void {
        switch (expr.*) {
            .rule_ref => |rule_ref| {
                // Don't increment expr_index here - it will be incremented in writeExprForAST
                const escaped_name = try escapeZigString(rule_ref.name.value, self.allocator);
                defer self.allocator.free(escaped_name);

                try self.writer.print("    const rule_ref_{}_{} = try allocator.create(ast.RuleRefExpr);\n", .{self.rule_index, self.expr_index + 1});
                try self.writer.print("    rule_ref_{}_{}.* = .{{\n", .{self.rule_index, self.expr_index + 1});
                try self.writer.print("        .pos = ast.Pos{{ .line = {}, .column = {}, .offset = {} }},\n",
                    .{ rule_ref.pos.line, rule_ref.pos.column, rule_ref.pos.offset });
                try self.writer.print("        .name = .{{\n            .pos = ast.Pos{{ .line = {}, .column = {}, .offset = {} }},\n            .value = \"{s}\",\n        }},\n",
                    .{rule_ref.name.pos.line, rule_ref.name.pos.column, rule_ref.name.pos.offset, escaped_name});
                try self.writer.writeAll("        .nullable = false,\n");
                try self.writer.print("    }};\n", .{});

                // Also create Expression wrapper for this rule_ref
                try self.writer.print("    const rule_ref_expr_{}_{} = try allocator.create(ast.Expression);\n", .{self.rule_index, self.expr_index + 1});
                try self.writer.print("    rule_ref_expr_{}_{}.* = .{{ .rule_ref = rule_ref_{}_{} }};\n\n", .{self.rule_index, self.expr_index + 1, self.rule_index, self.expr_index + 1});
            },
            .action => |act| try self.declareRuleRefExprs(act.expr),
            .and_expr => |and_expr| try self.declareRuleRefExprs(and_expr.expr),
            .choice => |choice| {
                for (choice.alternatives.items) |e| try self.declareRuleRefExprs(e);
            },
            .labeled => |labeled| try self.declareRuleRefExprs(labeled.expr),
            .not => |not_expr| try self.declareRuleRefExprs(not_expr.expr),
            .one_or_more => |one_or_more| try self.declareRuleRefExprs(one_or_more.expr),
            .seq => |seq| {
                for (seq.exprs.items) |e| try self.declareRuleRefExprs(e);
            },
            .zero_or_more => |zero_or_more| try self.declareRuleRefExprs(zero_or_more.expr),
            .zero_or_one => |zero_or_one| try self.declareRuleRefExprs(zero_or_one.expr),
            .recovery => |recovery| {
                try self.declareRuleRefExprs(recovery.expr);
                try self.declareRuleRefExprs(recovery.recover_expr);
            },
            // These types don't contain nested expressions that need RuleRefExpr
            .and_code, .not_code, .state_code, .any_matcher, .char_class_matcher, .lit_matcher, .throw => {},
        }
    }

    fn writeRuleDefinition(self: *Builder, r: *ast.Rule) !void {
        try self.writer.writeAll("        .{\n");
        try self.writer.print("            .name = ast.Identifier{{ .pos = ast.Pos{{ .line = {}, .column = {}, .offset = {} }}, .value = \"{s}\" }},\n",
            .{ r.pos.line, r.pos.column, r.pos.offset, r.name.value });

        try self.writer.print("            .display_name = ast.StringLit{{ .pos = ast.Pos{{ .line = {}, .column = {}, .offset = {} }}, .value = \"{s}\" }},\n",
            .{ r.display_name.pos.line, r.display_name.pos.column, r.display_name.pos.offset, r.display_name.value });

        try self.writer.writeAll("            .expr = null,\n"); // Need proper expression serialization
        try self.writer.writeAll("        },\n");
    }

    fn writeRuleRef(self: *Builder, r: *ast.Rule) !void {
        if (r.name.value.len == 0) return;

        self.expr_index = 0;
        self.rule_name = r.name.value;

        try self.writer.writeAll("    &.{\n");
        try self.writer.print("        .name = \"{s}\",\n", .{r.name.value});

        if (r.display_name.value.len > 0) {
            try self.writer.print("        .display_name = \"{s}\",\n", .{r.display_name.value});
        }

        const pos = r.pos;
        try self.writer.print("        .pos = Position{{ .line = {d}, .column = {d}, .offset = {d} }},\n",
            .{ pos.line, pos.column, pos.offset });

        try self.writer.writeAll("        .expr = ");
        try self.writeExpr(r.expr);

        if (r.leader) {
            try self.writer.writeAll("        .leader = true,\n");
        }
        if (r.left_recursive) {
            try self.writer.writeAll("        .left_recursive = true,\n");
        }

        try self.writer.writeAll("    },\n");
    }

    fn writeExpr(self: *Builder, expr: *ast.Expression) BuilderError!void {
        self.expr_index += 1;

        switch (expr.*) {
            .action => |act| try self.writeActionExpr(act),
            .and_code => |and_code| try self.writeAndCodeExpr(and_code),
            .and_expr => |and_expr| try self.writeAndExpr(and_expr),
            .any_matcher => |any| try self.writeAnyMatcher(any),
            .char_class_matcher => |char_class| try self.writeCharClassMatcher(char_class),
            .choice => |choice| try self.writeChoiceExpr(choice),
            .labeled => |labeled| try self.writeLabeledExpr(labeled),
            .lit_matcher => |lit| try self.writeLitMatcher(lit),
            .not_code => |not_code| try self.writeNotCodeExpr(not_code),
            .not => |not_expr| try self.writeNotExpr(not_expr),
            .one_or_more => |one_or_more| try self.writeOneOrMoreExpr(one_or_more),
            .recovery => |recovery| try self.writeRecoveryExpr(recovery),
            .rule_ref => |rule_ref| try self.writeRuleRefExpr(rule_ref),
            .seq => |seq| try self.writeSeqExpr(seq),
            .state_code => |state_code| try self.writeStateCodeExpr(state_code),
            .throw => |throw| try self.writeThrowExpr(throw),
            .zero_or_more => |zero_or_more| try self.writeZeroOrMoreExpr(zero_or_more),
            .zero_or_one => |zero_or_one| try self.writeZeroOrOneExpr(zero_or_one),
        }
    }

    fn writeActionExpr(self: *Builder, act: *ast.ActionExpr) BuilderError!void {
        try self.writer.writeAll("&ActionExpr{\n");
        const pos = act.pos;
        try self.writer.print("    .pos = Position{{ .line = {d}, .column = {d}, .offset = {d} }},\n",
            .{ pos.line, pos.column, pos.offset });

        if (act.func_ix == 0) {
            act.func_ix = self.expr_index;
        }

        try self.writer.print("    .run = parser.call{s},\n", .{self.rule_name});
        try self.writer.writeAll("    .expr = ");
        try self.writeExpr(act.expr);
        try self.writer.writeAll(",\n},\n");
    }

    fn writeAndCodeExpr(self: *Builder, and_code: *ast.AndCodeExpr) BuilderError!void {
        try self.writer.writeAll("&AndCodeExpr{\n");
        const pos = and_code.pos;
        try self.writer.print("    .pos = Position{{ .line = {}, .column = {}, .offset = {} }},\n",
            .{ pos.line, pos.column, pos.offset });

        if (and_code.func_ix == 0) {
            and_code.func_ix = self.expr_index;
        }

        try self.writer.print("    .run = parser.call{s},\n", .{self.rule_name});
        try self.writer.writeAll("},\n");
    }

    fn writeAndExpr(self: *Builder, and_expr: *ast.AndExpr) BuilderError!void {
        try self.writer.writeAll("&AndExpr{\n");
        const pos = and_expr.pos;
        try self.writer.print("    .pos = Position{{ .line = {}, .column = {}, .offset = {} }},\n",
            .{ pos.line, pos.column, pos.offset });

        try self.writer.writeAll("    .expr = ");
        try self.writeExpr(and_expr.expr);
        try self.writer.writeAll(",\n},\n");
    }

    fn writeAnyMatcher(self: *Builder, any: *ast.AnyMatcher) BuilderError!void {
        try self.writer.writeAll("&AnyMatcher{\n");
        const pos = any.pos;
        try self.writer.print("    .pos = Position{{ .line = {}, .column = {}, .offset = {} }},\n",
            .{ pos.line, pos.column, pos.offset });
        try self.writer.writeAll("},\n");
    }

    fn writeCharClassMatcher(self: *Builder, char_class: *ast.CharClassMatcher) BuilderError!void {
        try self.writer.writeAll("&CharClassMatcher{\n");
        const pos = char_class.pos;
        try self.writer.print("    .pos = Position{{ .line = {}, .column = {}, .offset = {} }},\n",
            .{ pos.line, pos.column, pos.offset });

        try self.writer.print("    .value = \"{s}\",\n", .{char_class.value});

        if (char_class.chars.items.len > 0) {
            try self.writer.writeAll("    .chars = &[_]u21{\n");
            for (char_class.chars.items) |ch| {
                if (char_class.ignore_case) {
                    try self.writer.print("        {d},\n", .{std.ascii.toLower(ch)});
                } else {
                    try self.writer.print("        {d},\n", .{ch});
                }
            }
            try self.writer.writeAll("    },\n");
        }

        if (char_class.ranges.items.len > 0) {
            try self.writer.writeAll("    .ranges = &[_]struct { u21, u21 }{\n");
            for (char_class.ranges.items) |range| {
                if (char_class.ignore_case) {
                    try self.writer.print("        .{{ {}, {} }},\n",
                        .{ std.ascii.toLower(range[0]), std.ascii.toLower(range[1]) });
                } else {
                    try self.writer.print("        .{{ {}, {} }},\n", .{ range[0], range[1] });
                }
            }
            try self.writer.writeAll("    },\n");
        }

        if (self.options.basic_latin_lookup_table) {
            try self.writer.writeAll("    .basic_latin_chars = ");
            // Would implement BasicLatinLookup equivalent
            try self.writer.writeAll("undefined,\n");
        }

        try self.writer.print("    .ignore_case = {},\n", .{char_class.ignore_case});
        try self.writer.print("    .inverted = {},\n", .{char_class.inverted});
        try self.writer.writeAll("},\n");
    }

    fn writeChoiceExpr(self: *Builder, choice: *ast.ChoiceExpr) BuilderError!void {
        try self.writer.writeAll("&ChoiceExpr{\n");
        const pos = choice.pos;
        try self.writer.print("    .pos = Position{{ .line = {}, .column = {}, .offset = {} }},\n",
            .{ pos.line, pos.column, pos.offset });

        if (choice.alternatives.items.len > 0) {
            try self.writer.writeAll("    .alternatives = &[_]Expression{\n");
            for (choice.alternatives.items) |alt| {
                try self.writeExpr(alt);
            }
            try self.writer.writeAll("    },\n");
        }
        try self.writer.writeAll("},\n");
    }

    fn writeLabeledExpr(self: *Builder, labeled: *ast.LabeledExpr) BuilderError!void {
        try self.writer.writeAll("&LabeledExpr{\n");
        const pos = labeled.pos;
        try self.writer.print("    .pos = Position{{ .line = {}, .column = {}, .offset = {} }},\n",
            .{ pos.line, pos.column, pos.offset });

        if (labeled.label.value.len > 0) {
            try self.writer.print("    .label = \"{s}\",\n", .{labeled.label.value});
        }

        try self.writer.writeAll("    .expr = ");
        try self.writeExpr(labeled.expr);
        try self.writer.writeAll(",\n},\n");
    }

    fn writeLitMatcher(self: *Builder, lit: *ast.LitMatcher) BuilderError!void {
        try self.writer.writeAll("&LitMatcher{\n");
        const pos = lit.pos;
        try self.writer.print("    .pos = Position{{ .line = {}, .column = {}, .offset = {} }},\n",
            .{ pos.line, pos.column, pos.offset });

        if (lit.ignore_case) {
            const output = try self.allocator.dupe(u8, lit.value);
            defer self.allocator.free(output);
            _ = std.ascii.lowerString(output, lit.value);
            try self.writer.print("    .value = \"{s}\",\n", .{output});
        } else {
            try self.writer.print("    .value = \"{s}\",\n", .{lit.value});
        }

        try self.writer.print("    .ignore_case = {},\n", .{lit.ignore_case});
        try self.writer.print("    .want = \"{s}\",\n", .{lit.value});
        try self.writer.writeAll("},\n");
    }

    fn writeNotCodeExpr(self: *Builder, not_code: *ast.NotCodeExpr) BuilderError!void {
        try self.writer.writeAll("&NotCodeExpr{\n");
        const pos = not_code.pos;
        try self.writer.print("    .pos = Position{{ .line = {}, .column = {}, .offset = {} }},\n",
            .{ pos.line, pos.column, pos.offset });

        if (not_code.func_ix == 0) {
            not_code.func_ix = self.expr_index;
        }

        try self.writer.print("    .run = parser.call{s},\n", .{self.rule_name});
        try self.writer.writeAll("},\n");
    }

    fn writeNotExpr(self: *Builder, not_expr: *ast.NotExpr) BuilderError!void {
        try self.writer.writeAll("&NotExpr{\n");
        const pos = not_expr.pos;
        try self.writer.print("    .pos = Position{{ .line = {}, .column = {}, .offset = {} }},\n",
            .{ pos.line, pos.column, pos.offset });

        try self.writer.writeAll("    .expr = ");
        try self.writeExpr(not_expr.expr);
        try self.writer.writeAll(",\n},\n");
    }

    fn writeOneOrMoreExpr(self: *Builder, one_or_more: *ast.OneOrMoreExpr) BuilderError!void {
        try self.writer.writeAll("&OneOrMoreExpr{\n");
        const pos = one_or_more.pos;
        try self.writer.print("    .pos = Position{{ .line = {}, .column = {}, .offset = {} }},\n",
            .{ pos.line, pos.column, pos.offset });

        try self.writer.writeAll("    .expr = ");
        try self.writeExpr(one_or_more.expr);
        try self.writer.writeAll(",\n},\n");
    }

    fn writeRecoveryExpr(self: *Builder, recovery: *ast.RecoveryExpr) BuilderError!void {
        try self.writer.writeAll("&RecoveryExpr{\n");
        const pos = recovery.pos;
        try self.writer.print("    .pos = Position{{ .line = {}, .column = {}, .offset = {} }},\n",
            .{ pos.line, pos.column, pos.offset });

        try self.writer.writeAll("    .expr = ");
        try self.writeExpr(recovery.expr);
        try self.writer.writeAll("    .recover_expr = ");
        try self.writeExpr(recovery.recover_expr);

        try self.writer.writeAll("    .labels = &[_][]const u8{\n");
        for (recovery.labels.items) |label| {
            try self.writer.print("        \"{s}\",\n", .{label});
        }
        try self.writer.writeAll("    },\n},\n");
    }

    fn writeRuleRefExpr(self: *Builder, rule_ref: *ast.RuleRefExpr) BuilderError!void {
        try self.writer.writeAll("&RuleRefExpr{\n");
        const pos = rule_ref.pos;
        try self.writer.print("    .pos = Position{{ .line = {}, .column = {}, .offset = {} }},\n",
            .{ pos.line, pos.column, pos.offset });

        try self.writer.print("    .name = \"{s}\",\n", .{rule_ref.name.value});
        try self.writer.writeAll("},\n");
    }

    fn writeSeqExpr(self: *Builder, seq: *ast.SeqExpr) BuilderError!void {
        try self.writer.writeAll("&SeqExpr{\n");
        const pos = seq.pos;
        try self.writer.print("    .pos = Position{{ .line = {}, .column = {}, .offset = {} }},\n",
            .{ pos.line, pos.column, pos.offset });

        if (seq.exprs.items.len > 0) {
            try self.writer.writeAll("    .exprs = &[_]Expression{\n");
            for (seq.exprs.items) |expr| {
                try self.writeExpr(expr);
            }
            try self.writer.writeAll("    },\n");
        }
        try self.writer.writeAll("},\n");
    }

    fn writeStateCodeExpr(self: *Builder, state_code: *ast.StateCodeExpr) BuilderError!void {
        self.options.global_state = true;
        try self.writer.writeAll("&StateCodeExpr{\n");
        const pos = state_code.pos;
        try self.writer.print("    .pos = Position{{ .line = {}, .column = {}, .offset = {} }},\n",
            .{ pos.line, pos.column, pos.offset });

        if (state_code.func_ix == 0) {
            state_code.func_ix = self.expr_index;
        }

        try self.writer.print("    .run = parser.call{s},\n", .{self.rule_name});
        try self.writer.writeAll("},\n");
    }

    fn writeThrowExpr(self: *Builder, throw: *ast.ThrowExpr) BuilderError!void {
        try self.writer.writeAll("&ThrowExpr{\n");
        const pos = throw.pos;
        try self.writer.print("    .pos = Position{{ .line = {}, .column = {}, .offset = {} }},\n",
            .{ pos.line, pos.column, pos.offset });

        try self.writer.print("    .label = \"{s}\",\n", .{throw.label});
        try self.writer.writeAll("},\n");
    }

    fn writeZeroOrMoreExpr(self: *Builder, zero_or_more: *ast.ZeroOrMoreExpr) BuilderError!void {
        try self.writer.writeAll("&ZeroOrMoreExpr{\n");
        const pos = zero_or_more.pos;
        try self.writer.print("    .pos = Position{{ .line = {}, .column = {}, .offset = {} }},\n",
            .{ pos.line, pos.column, pos.offset });

        try self.writer.writeAll("    .expr = ");
        try self.writeExpr(zero_or_more.expr);
        try self.writer.writeAll(",\n},\n");
    }

    fn writeZeroOrOneExpr(self: *Builder, zero_or_one: *ast.ZeroOrOneExpr) BuilderError!void {
        try self.writer.writeAll("&ZeroOrOneExpr{\n");
        const pos = zero_or_one.pos;
        try self.writer.print("    .pos = Position{{ .line = {}, .column = {}, .offset = {} }},\n",
            .{ pos.line, pos.column, pos.offset });

        try self.writer.writeAll("    .expr = ");
        try self.writeExpr(zero_or_one.expr);
        try self.writer.writeAll(",\n},\n");
    }

    fn writeRuleCode(self: *Builder, rule: *ast.Rule) !void {
        if (rule.name.value.len == 0) return;

        self.rule_name = rule.name.value;
        self.expr_index = 0;
        try self.pushArgsSet();

        // Collect all possible parameters from labels
        try self.collectParams(rule.expr);
        const all_params = self.getCurrentParams();

        // Generate action function for this rule
        try self.writer.print("// Action function for rule: {s}\n", .{rule.name.value});
        try self.writer.print("fn on{s}(c: *interpreter.Current", .{rule.name.value});

        // Add all parameters
        for (all_params.items) |param| {
            try self.writer.print(", {s}: interpreter.Value", .{param});
        }
        try self.writer.writeAll(") !interpreter.Value {\n");

        // Analyze which parameters are actually used in the action code
        const used_params = try self.analyzeUsedParams(rule.expr);

        // Check if 'c' parameter is used
        const c_is_used = for (used_params.items) |used| {
            if (std.mem.eql(u8, used, "c")) {
                break true;
            }
        } else false;

        // Add _ = c; if c is not used
        if (!c_is_used) {
            try self.writer.writeAll("    _ = c;\n");
        }

        // Add _ = param; only for UNUSED parameters to suppress unused warnings
        // This is Zig's standard way to mark parameters as intentionally unused
        for (all_params.items) |param| {
            const is_used = for (used_params.items) |used| {
                if (std.mem.eql(u8, used, param)) {
                    break true;
                }
            } else false;

            if (!is_used) {
                try self.writer.print("    _ = {s};\n", .{param});
            }
        }

        // Generate action code
        try self.writeExprCode(rule.expr);

        try self.writer.writeAll("}\n\n");
        self.popArgsSet();
    }

    /// Analyze which parameters are referenced in the action code
    fn analyzeUsedParams(self: *Builder, expr: *const ast.Expression) !std.ArrayList([]const u8) {
        var used = try std.ArrayList([]const u8).initCapacity(self.allocator, 0);
        errdefer used.deinit(self.allocator);

        // Collect action code from the expression
        var action_codes = try std.ArrayList([]const u8).initCapacity(self.allocator, 0);
        defer {
            for (action_codes.items) |code| {
                self.allocator.free(code);
            }
            action_codes.deinit(self.allocator);
        }

        try self.collectActionCode(expr, &action_codes);

        // Analyze each action code for parameter references
        for (action_codes.items) |code| {
            try self.findParamReferences(code, &used);
        }

        // Deduplicate and return
        var result = try std.ArrayList([]const u8).initCapacity(self.allocator, used.items.len);
        for (used.items) |param| {
            const already_exists = for (result.items) |p| {
                if (std.mem.eql(u8, p, param)) break true;
            } else false;
            if (!already_exists) {
                try result.append(self.allocator, param);
            }
        }
        return result;
    }

    /// Collect all action code strings from an expression
    fn collectActionCode(self: *Builder, expr: *const ast.Expression, codes: *std.ArrayList([]const u8)) !void {
        switch (expr.*) {
            .action => |act| {
                try codes.append(self.allocator, try self.allocator.dupe(u8, act.code.value));
                try self.collectActionCode(act.expr, codes);
            },
            .seq => |seq| {
                for (seq.exprs.items) |sub| {
                    try self.collectActionCode(sub, codes);
                }
            },
            .choice => |choice| {
                for (choice.alternatives.items) |alt| {
                    try self.collectActionCode(alt, codes);
                }
            },
            .labeled => |labeled| {
                try self.collectActionCode(labeled.expr, codes);
            },
            .zero_or_one => |z| try self.collectActionCode(z.expr, codes),
            .zero_or_more => |z| try self.collectActionCode(z.expr, codes),
            .one_or_more => |o| try self.collectActionCode(o.expr, codes),
            .and_expr => |and_expr| try self.collectActionCode(and_expr.expr, codes),
            .not => |not_expr| try self.collectActionCode(not_expr.expr, codes),
            else => {}, // Other types don't contain action code
        }
    }

    /// Find parameter references in code string
    fn findParamReferences(self: *Builder, code: []const u8, used: *std.ArrayList([]const u8)) !void {
        // Simple heuristic: find identifiers that match parameter names
        // Look for patterns like "param", "param.", "param("
        var i: usize = 0;
        while (i < code.len) {
            // Skip non-identifier characters
            if (!isIdentifierStart(code[i])) {
                i += 1;
                continue;
            }

            // Found identifier start
            const start = i;
            while (i < code.len and isIdentifierContinue(code[i])) {
                i += 1;
            }

            const ident = code[start..i];

            // Check if this is a parameter reference
            // (heuristic: identifier followed by '.', '(', or end of statement)
            if (i < code.len) {
                const next_char = code[i];
                if (next_char == '.' or next_char == '(' or next_char == ' ' or
                    next_char == '\n' or next_char == ',' or next_char == ';' or
                    next_char == ')' or next_char == '}' or next_char == '=') {
                    // Check if this identifier is a known parameter
                    // For now, assume any identifier could be a parameter
                    // In a more complete implementation, we'd check against self.params
                    try used.append(self.allocator, try self.allocator.dupe(u8, ident));
                }
            }
        }
    }

    fn isIdentifierStart(c: u8) bool {
        return (c >= 'a' and c <= 'z') or (c >= 'A' and c <= 'Z') or c == '_';
    }

    fn isIdentifierContinue(c: u8) bool {
        return isIdentifierStart(c) or (c >= '0' and c <= '9');
    }

    fn pushArgsSet(self: *Builder) !void {
        try self.args_stack.append(self.allocator, try std.ArrayList([]const u8).initCapacity(self.allocator, 0));
    }

    fn popArgsSet(self: *Builder) void {
        if (self.args_stack.items.len > 0) {
            var old_set = self.args_stack.orderedRemove(self.args_stack.items.len - 1);
            old_set.deinit(self.allocator);
        }
    }

    fn addArg(self: *Builder, arg: *ast.Identifier) !void {
        if (self.args_stack.items.len == 0) return;

        const current_set = &self.args_stack.items[self.args_stack.items.len - 1];
        try current_set.append(self.allocator, arg.value);
    }

    fn collectParams(self: *Builder, expr: *ast.Expression) !void {
        switch (expr.*) {
            .labeled => |labeled| {
                try self.addArg(labeled.label);
                try self.collectParams(labeled.expr);
            },
            .seq => |seq| {
                for (seq.exprs.items) |sub| {
                    try self.collectParams(sub);
                }
            },
            .choice => |choice| {
                for (choice.alternatives.items) |alt| {
                    try self.collectParams(alt);
                }
            },
            .action => |action| {
                try self.collectParams(action.expr);
            },
            // Other expression types don't have labels
            else => {},
        }
    }

    fn getCurrentParams(self: *Builder) std.ArrayList([]const u8) {
        if (self.args_stack.items.len == 0) {
            return std.ArrayList([]const u8).initCapacity(self.allocator, 0) catch unreachable;
        }
        return self.args_stack.items[self.args_stack.items.len - 1];
    }

    fn writeExprCode(self: *Builder, expr: *ast.Expression) !void {
        switch (expr.*) {
            .action => |act| {
                try self.writeExprCode(act.expr);
                try self.writeActionExprCode(act);
            },
            .and_code => |and_code| try self.writeAndCodeExprCode(and_code),
            .labeled => |labeled| {
                try self.addArg(labeled.label);
                try self.pushArgsSet();
                try self.writeExprCode(labeled.expr);
                self.popArgsSet();
            },
            .not_code => |not_code| try self.writeNotCodeExprCode(not_code),
            .and_expr => |and_expr| {
                try self.pushArgsSet();
                try self.writeExprCode(and_expr.expr);
                self.popArgsSet();
            },
            .choice => |choice| {
                for (choice.alternatives.items) |alt| {
                    try self.pushArgsSet();
                    try self.writeExprCode(alt);
                    self.popArgsSet();
                }
            },
            .not => |not_expr| {
                try self.pushArgsSet();
                try self.writeExprCode(not_expr.expr);
                self.popArgsSet();
            },
            .one_or_more => |one_or_more| {
                try self.pushArgsSet();
                try self.writeExprCode(one_or_more.expr);
                self.popArgsSet();
            },
            .recovery => |recovery| {
                try self.pushArgsSet();
                try self.writeExprCode(recovery.expr);
                try self.writeExprCode(recovery.recover_expr);
                self.popArgsSet();
            },
            .seq => |seq| {
                for (seq.exprs.items) |sub| {
                    try self.writeExprCode(sub);
                }
            },
            .state_code => |state_code| try self.writeStateCodeExprCode(state_code),
            .zero_or_more => |zero_or_more| {
                try self.pushArgsSet();
                try self.writeExprCode(zero_or_more.expr);
                self.popArgsSet();
            },
            .zero_or_one => |zero_or_one| {
                try self.pushArgsSet();
                try self.writeExprCode(zero_or_one.expr);
                self.popArgsSet();
            },
            else => {}, // Other types don't generate code
        }
    }

    fn writeActionExprCode(self: *Builder, act: *ast.ActionExpr) !void {
        // Write the user's action code
        // For now, we just extract the code and write it
        // TODO: Process the code to handle variable references
        const code = act.code.value;

        if (code.len > 2) { // Not just {}
            // Extract code between braces
            const inner_code = if (code.len > 2 and code[0] == '{')
                code[1 .. code.len-1]
            else
                code;

            // Write the code with proper indentation
            try self.writer.writeAll("    ");
            try self.writer.writeAll(inner_code);
            try self.writer.writeAll("\n");
        }
    }

    fn writeAndCodeExprCode(self: *Builder, and_code: *ast.AndCodeExpr) !void {
        if (and_code.func_ix > 0) {
            try self.writeFunc(CALL_PRED_FUNC_TEMPLATE, ON_PRED_FUNC_TEMPLATE, and_code.func_ix, and_code.code.value);
            and_code.func_ix = 0; // prevent duplicates
        }
    }

    fn writeNotCodeExprCode(self: *Builder, not_code: *ast.NotCodeExpr) !void {
        if (not_code.func_ix > 0) {
            try self.writeFunc(CALL_PRED_FUNC_TEMPLATE, ON_PRED_FUNC_TEMPLATE, not_code.func_ix, not_code.code.value);
            not_code.func_ix = 0; // prevent duplicates
        }
    }

    fn writeStateCodeExprCode(self: *Builder, state_code: *ast.StateCodeExpr) !void {
        if (state_code.func_ix > 0) {
            try self.writeFunc(CALL_STATE_FUNC_TEMPLATE, ON_STATE_FUNC_TEMPLATE, state_code.func_ix, state_code.code.value);
            state_code.func_ix = 0; // prevent duplicates
        }
    }

    fn writeFunc(self: *Builder, comptime call_template: []const u8, comptime func_template: []const u8, func_ix: usize, code: []const u8) !void {
        _ = func_ix;
        
        if (code.len <= 2) return; // empty code block {}

        // Remove braces and trim whitespace
        // const val = std.mem.trim(u8, code[1..code.len-1], " \t\r\n");

        // Generate arguments list
        var args_buffer: std.ArrayList(u8) = .empty;
        defer args_buffer.deinit(self.allocator);

        if (self.args_stack.items.len > 0) {
            const current_set = &self.args_stack.items[self.args_stack.items.len - 1];
            for (current_set.items, 0..) |arg, i| {
                if (i > 0) {
                    try args_buffer.appendSlice(self.allocator, ", ");
                }
                try args_buffer.appendSlice(self.allocator, arg);
            }
        }
        if (args_buffer.items.len > 0) {
            try args_buffer.appendSlice(self.allocator, " any");
        }

        const fn_name = self.rule_name;

        // Write function definition
        try self.writer.print(func_template,
            .{ self.options.receiver_name, fn_name, args_buffer.items });

        // Generate stack access arguments
        args_buffer.clearRetainingCapacity();
        var writer = std.io.Writer.Allocating.fromArrayList(self.allocator, &args_buffer).writer;

        if (self.args_stack.items.len > 0) {
            const current_set = &self.args_stack.items[self.args_stack.items.len - 1];
            for (current_set.items, 0..) |arg, i| {
                if (i > 0) {
                    try args_buffer.appendSlice(self.allocator, ", ");
                }

                try writer.print("\"{s}\"", .{arg});
            }
        }

        // Write function call
        try self.writer.print(call_template, .{ fn_name, "todo", args_buffer.items });
    }

    fn writeStaticCode(self: *Builder) !void {
        // Write ParserError enum
        try self.writer.writeAll("const ParserError = error{\n");
        try self.writer.writeAll("    ParseError,\n");
        try self.writer.writeAll("    UnexpectedToken,\n");
        try self.writer.writeAll("    MissingExpression,\n");
        try self.writer.writeAll("    UnterminatedExpression,\n");
        try self.writer.writeAll("    OutOfMemory,\n");
        try self.writer.writeAll("};\n\n");

        // Write basic Parser struct definition
        try self.writer.writeAll("/// Parser holds the state to parse PEG grammar into an abstract syntax tree (AST).\n");
        try self.writer.writeAll("pub const Parser = struct {\n");
        try self.writer.writeAll("    allocator: std.mem.Allocator,\n");
        try self.writer.writeAll("    filename: []const u8,\n");
        try self.writer.writeAll("    reader: *std.io.Reader,\n");

        // Scanner-related fields
        try self.writer.writeAll("    scanner: ?*Scanner,\n");  // Scanner will be defined in scanner.zig - optional pointer
        try self.writer.writeAll("    tok: Token,\n");        // Current token
        try self.writer.writeAll("    peek_tok: Token,\n");    // Peek token (next one in stream)

        // Debug and error handling fields
        try self.writer.writeAll("    debug: bool = false,\n");

        // Add scanner and token imports
        try self.writer.writeAll("\n");
        try self.writer.writeAll("    // Import scanner and token definitions\n");
        try self.writer.writeAll("    const Scanner = @import(\"scanner.zig\").Scanner;\n");
        try self.writer.writeAll("    const Token = @import(\"scanner.zig\").Token;\n");

        // Write init method (update to include filename and reader)
        try self.writer.writeAll("\n");
        try self.writer.writeAll("    pub fn init(allocator: std.mem.Allocator, filename: []const u8, reader: *std.io.Reader) Parser {\n");
        try self.writer.writeAll("        // Initialize with scanner = null and empty tokens\n");
        try self.writer.writeAll("        var init_tok = Token{\n");
        try self.writer.writeAll("            .id = .invalid,\n");  // Assume Token has an id field with enum type
        try self.writer.writeAll("            .lit = \"\",\n");     // Assume Token has a lit field
        try self.writer.writeAll("        };\n");
        try self.writer.writeAll("\n");
        try self.writer.writeAll("        return Parser{\n");
        try self.writer.writeAll("            .allocator = allocator,\n");
        try self.writer.writeAll("            .filename = filename,\n");
        try self.writer.writeAll("            .reader = reader,\n");
        try self.writer.writeAll("            .scanner = null,\n");
        try self.writer.writeAll("            .tok = init_tok,\n");
        try self.writer.writeAll("            .peek_tok = init_tok,\n");
        try self.writer.writeAll("        };\n");
        try self.writer.writeAll("    }\n");

        // Write parse method framework
        try self.writer.writeAll("\n");
        try self.writer.writeAll("    /// Parse parses the data from the reader and generates the AST\n");
        try self.writer.writeAll("    /// or returns an error if it fails. The filename is used as information\n");
        try self.writer.writeAll("    /// in the error messages.\n");
        try self.writer.writeAll("    pub fn parse(self: *Parser) !*ast.Grammar {\n");

        // Initialize scanner
        try self.writer.writeAll("        // Initialize scanner\n");
        try self.writer.writeAll("        self.scanner = try Scanner.init(self.allocator, self.filename, self.reader, null);\n");
        try self.writer.writeAll("        defer if (self.scanner) |scanner| scanner.deinit();\n");
        try self.writer.writeAll("\n");

        // Read first two tokens (current and peek)
        try self.writer.writeAll("        // Read first two tokens\n");
        try self.writer.writeAll("        self.read();\n");
        try self.writer.writeAll("        self.read();\n");
        try self.writer.writeAll("\n");

        // Call grammar rule (the start symbol of the PEG grammar)
        try self.writer.writeAll("        // Parse grammar using the root rule (Grammar)\n");
        try self.writer.writeAll("        const grammar = try self.grammar();\n");
        try self.writer.writeAll("\n");

        // Clean up and return
        try self.writer.writeAll("        // Return the parsed grammar\n");
        try self.writer.writeAll("        return grammar;\n");
        try self.writer.writeAll("    }\n");

        // Write deinit method
        try self.writer.writeAll("\n");
        try self.writer.writeAll("    pub fn deinit(_: *Parser) void {\n");
        try self.writer.writeAll("        // TODO: Implement cleanup logic\n");
        try self.writer.writeAll("    }\n");

        // Close Parser struct
        try self.writer.writeAll("};\n\n");

        // Write range table comment if needed
        if (self.range_table) {
            try self.writer.writeAll("// Range table code would be written here\n");
        }
    }

    pub fn deinit(self: *Builder) void {
        while (self.args_stack.items.len > 0) {
            var old_set = self.args_stack.orderedRemove(self.args_stack.items.len - 1);
            old_set.deinit(self.allocator);
        }
        self.args_stack.deinit(self.allocator);
    }
};

/// Public API function to build a parser
pub fn buildParser(writer: std.io.Writer, grammar: *ast.Grammar, options: Options) !void {
    var builder = Builder.init(std.heap.page_allocator, writer, options);
    defer builder.deinit();

    try builder.buildParser(grammar);
}